# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            andrew
tagline:          'the personal blog of Andrew Bridges'
description:      'the personal blog of Andrew Bridges'
url:              http://nwandabridges.github.io
baseurl:          /

author:
  name:           'Andrew Bridges'
  url:            https://twitter.com/nwandabridges

paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/nwandabridges/nwandabridges.github.io
